apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rollout-statefulset
spec:
  schedule: "0 */4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rollout-statefulset
            image: kubectl
            command: ["/bin/sh", "-c"]
            args:
            - |
              set -e
              set -x
              old_hash=$(kubectl get statefulset neon-proxy -o jsonpath='{.metadata.annotations.hashed-image}')
              new_hash=$(kubectl inspect image neonlabsorg/proxy:v0.15.4 | md5sum | cut -f1 -d' ')
              if [ "$old_hash" != "$new_hash" ]; then
                kubectl set image statefulset neon-proxy neon-proxy=neonlabsorg/proxy:v0.15.4
              else
                echo "No update available"
              fi
          restartPolicy: OnFailure
