apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-tracer.yaml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: tracer-db
  name: tracer-db
  namespace: neon-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tracer-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-tracer.yaml
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: tracer-db
    spec:
      containers:
        - args:
            - postgres
            - -c
            - max_connections=1000
          env:
            - name: POSTGRES_DB
              value: solana
            - name: POSTGRES_PASSWORD
              value: solana-pass
            - name: POSTGRES_USER
              value: solana-user
          image: neonlabsorg/neon-accountsdb:v1.13.4-neon-tracer
          livenessProbe:
            exec:
              command:
                - pg_isready -h tracer_db -p 5432 -U solana-user
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 10
          name: tracer-db
          ports:
            - containerPort: 5432
          resources: {}
      hostname: tracer-db
      restartPolicy: Always
status: {}
