apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-tracer.yaml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: neon-tracer
  name: neon-tracer
  namespace: neon-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neon-tracer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-tracer.yaml
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: neon-tracer
    spec:
      containers:
        - env:
            - name: EVM_LOADER
              value: 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io
            - name: INDEXER_DB_HOST
              value: postgres
            - name: INDEXER_DB_NAME
              value: neon-db
            - name: INDEXER_DB_PASSWORD
              value: neon-proxy-pass
            - name: INDEXER_DB_PORT
              value: "543222222222"
            - name: INDEXER_DB_USER
              value: neon-proxy
            - name: LISTEN_ADDR
              value: 0.0.0.0:8250
            - name: METRICS_IP
              value: 0.0.0.0
            - name: METRICS_PORT
              value: "9292"
            - name: MONITORING_INTERVAL_SEC
              value: "15"
            - name: NEON_CHAIN_ID
              value: "111"
            - name: NEON_TOKEN_MINT
              value: HPsV9Deocecw3GeZv1FkAPNCBRfuVyfw9MMwjwRe1xaU
            - name: RUST_BACKTRACE
              value: "1"
            - name: RUST_LOG
              value: neon=debug,metrics=debug
            - name: SOLANA_URL
              value: http://validator:8899
            - name: TRACER_DB_HOST
              value: tracer-db
            - name: TRACER_DB_NAME
              value: solana
            - name: TRACER_DB_PASSWORD
              value: solana-pass
            - name: TRACER_DB_PORT
              value: "5432"
            - name: TRACER_DB_USER
              value: solana-user
            - name: WEB3_PROXY
              value: http://proxy:9090/solana
          image: neonlabsorg/neon-tracer:ci-eip-1898
          name: neon-tracer
          ports:
            - containerPort: 8250
            - containerPort: 9292
          resources: {}
      hostname: neon-tracer
      restartPolicy: Always
status: {}
