apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-tracer.yaml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: neon-tracer
  name: neon-tracer
  namespace: neon-proxy
spec:
  ports:
    - name: "8250"
      port: 8250
      targetPort: 8250
    - name: "9292"
      port: 9292
      targetPort: 9292
    - name: 8250-tcp
      port: 8250
      targetPort: 8250
  selector:
    io.kompose.service: neon-tracer
status:
  loadBalancer: {}
