apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    use-proxy-protocol: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: proxy-svc
            port:
              number: 9090
        path: /
        pathType: Prefix
